//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""PlayerThird"",
            ""id"": ""075ec289-1fc7-417d-af9b-af4759989350"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""8644beb2-436d-4094-ae54-b6575516248f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""fac7ee99-3039-438e-9327-bfafdf21b67b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Roll"",
                    ""type"": ""Value"",
                    ""id"": ""e2ee2a7d-86cd-4fcf-aa8d-c0c9dbe08777"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Hover"",
                    ""type"": ""Value"",
                    ""id"": ""238508c9-4335-49ce-9397-ce55d3de7870"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""83c1797b-a72c-457b-8587-437bc87726f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveUpDown"",
                    ""type"": ""Value"",
                    ""id"": ""b7282fd6-d4b9-4ac8-9ee6-7faeeaefa643"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""eb0c44d9-93c4-481c-8a88-5685a2ba1dd6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""16b37e57-49b8-4be9-8c62-f28e39be0750"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""48d83af9-bab9-4859-98dc-ccca9775c164"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""aadb32e0-84b0-426f-9810-efff6f74da6b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8c71cb64-7601-41eb-a1b3-cb203cfa1ad9"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e4b18e5c-4fda-407c-80c7-fb588ad2c238"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""EQ"",
                    ""id"": ""5e962a87-4e07-470c-bdd9-e96ac9517d95"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""9bac2bf8-0a31-45ef-96ed-119c8960af7e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""4d5fd1a3-0468-4f33-b6a0-ed0fae3651c2"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b44d5cf9-a20e-4694-bc97-1fbb045f9be1"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""774bdad2-2398-4575-ab55-98541b0bbd8e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""LeftCtrlSpace"",
                    ""id"": ""78737060-4c76-41e5-98cf-1104623981d0"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUpDown"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8468db10-01c9-4231-997f-a5d3c590c5ac"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""aca01a91-89f1-4313-aafc-f580beade620"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""PlayerTop"",
            ""id"": ""0fae9da2-1901-4237-b840-88f81cc10e0b"",
            ""actions"": [
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""263c46ef-8530-4d42-a7ab-b8421577cc59"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseDelta"",
                    ""type"": ""Value"",
                    ""id"": ""933cc4fe-20b3-469c-ad1b-19ff22c0e458"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""188cb7af-eba0-4370-99f0-681dc6ab38a6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NormalShoot"",
                    ""type"": ""Button"",
                    ""id"": ""9d0866e0-abec-4cb8-aeb4-d0ef24bd6556"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""00c46c16-cc51-4481-9977-7e891d08af91"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae48b486-6e26-463f-b59c-6603a1a5a914"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""46018e52-9aae-4d06-ac62-420a8e65ada4"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""576189f1-0ed9-44be-8769-cc119103150e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""69efe525-aae7-4bd8-91af-aba3a72b4287"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0b22c807-5e00-43e3-8c77-61e7771fd151"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7109cce4-af85-4196-8671-ff78932bd4d8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7f0b5240-22a9-4087-a7b6-cbfe53177c3d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NormalShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PlayerTop"",
            ""bindingGroup"": ""PlayerTop"",
            ""devices"": []
        }
    ]
}");
        // PlayerThird
        m_PlayerThird = asset.FindActionMap("PlayerThird", throwIfNotFound: true);
        m_PlayerThird_Move = m_PlayerThird.FindAction("Move", throwIfNotFound: true);
        m_PlayerThird_Look = m_PlayerThird.FindAction("Look", throwIfNotFound: true);
        m_PlayerThird_Roll = m_PlayerThird.FindAction("Roll", throwIfNotFound: true);
        m_PlayerThird_Hover = m_PlayerThird.FindAction("Hover", throwIfNotFound: true);
        m_PlayerThird_Shoot = m_PlayerThird.FindAction("Shoot", throwIfNotFound: true);
        m_PlayerThird_MoveUpDown = m_PlayerThird.FindAction("MoveUpDown", throwIfNotFound: true);
        // PlayerTop
        m_PlayerTop = asset.FindActionMap("PlayerTop", throwIfNotFound: true);
        m_PlayerTop_MousePosition = m_PlayerTop.FindAction("MousePosition", throwIfNotFound: true);
        m_PlayerTop_MouseDelta = m_PlayerTop.FindAction("MouseDelta", throwIfNotFound: true);
        m_PlayerTop_Movement = m_PlayerTop.FindAction("Movement", throwIfNotFound: true);
        m_PlayerTop_NormalShoot = m_PlayerTop.FindAction("NormalShoot", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerThird
    private readonly InputActionMap m_PlayerThird;
    private List<IPlayerThirdActions> m_PlayerThirdActionsCallbackInterfaces = new List<IPlayerThirdActions>();
    private readonly InputAction m_PlayerThird_Move;
    private readonly InputAction m_PlayerThird_Look;
    private readonly InputAction m_PlayerThird_Roll;
    private readonly InputAction m_PlayerThird_Hover;
    private readonly InputAction m_PlayerThird_Shoot;
    private readonly InputAction m_PlayerThird_MoveUpDown;
    public struct PlayerThirdActions
    {
        private @Controls m_Wrapper;
        public PlayerThirdActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerThird_Move;
        public InputAction @Look => m_Wrapper.m_PlayerThird_Look;
        public InputAction @Roll => m_Wrapper.m_PlayerThird_Roll;
        public InputAction @Hover => m_Wrapper.m_PlayerThird_Hover;
        public InputAction @Shoot => m_Wrapper.m_PlayerThird_Shoot;
        public InputAction @MoveUpDown => m_Wrapper.m_PlayerThird_MoveUpDown;
        public InputActionMap Get() { return m_Wrapper.m_PlayerThird; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerThirdActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerThirdActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerThirdActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerThirdActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Roll.started += instance.OnRoll;
            @Roll.performed += instance.OnRoll;
            @Roll.canceled += instance.OnRoll;
            @Hover.started += instance.OnHover;
            @Hover.performed += instance.OnHover;
            @Hover.canceled += instance.OnHover;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @MoveUpDown.started += instance.OnMoveUpDown;
            @MoveUpDown.performed += instance.OnMoveUpDown;
            @MoveUpDown.canceled += instance.OnMoveUpDown;
        }

        private void UnregisterCallbacks(IPlayerThirdActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Roll.started -= instance.OnRoll;
            @Roll.performed -= instance.OnRoll;
            @Roll.canceled -= instance.OnRoll;
            @Hover.started -= instance.OnHover;
            @Hover.performed -= instance.OnHover;
            @Hover.canceled -= instance.OnHover;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @MoveUpDown.started -= instance.OnMoveUpDown;
            @MoveUpDown.performed -= instance.OnMoveUpDown;
            @MoveUpDown.canceled -= instance.OnMoveUpDown;
        }

        public void RemoveCallbacks(IPlayerThirdActions instance)
        {
            if (m_Wrapper.m_PlayerThirdActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerThirdActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerThirdActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerThirdActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerThirdActions @PlayerThird => new PlayerThirdActions(this);

    // PlayerTop
    private readonly InputActionMap m_PlayerTop;
    private List<IPlayerTopActions> m_PlayerTopActionsCallbackInterfaces = new List<IPlayerTopActions>();
    private readonly InputAction m_PlayerTop_MousePosition;
    private readonly InputAction m_PlayerTop_MouseDelta;
    private readonly InputAction m_PlayerTop_Movement;
    private readonly InputAction m_PlayerTop_NormalShoot;
    public struct PlayerTopActions
    {
        private @Controls m_Wrapper;
        public PlayerTopActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MousePosition => m_Wrapper.m_PlayerTop_MousePosition;
        public InputAction @MouseDelta => m_Wrapper.m_PlayerTop_MouseDelta;
        public InputAction @Movement => m_Wrapper.m_PlayerTop_Movement;
        public InputAction @NormalShoot => m_Wrapper.m_PlayerTop_NormalShoot;
        public InputActionMap Get() { return m_Wrapper.m_PlayerTop; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerTopActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerTopActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerTopActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerTopActionsCallbackInterfaces.Add(instance);
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
            @MouseDelta.started += instance.OnMouseDelta;
            @MouseDelta.performed += instance.OnMouseDelta;
            @MouseDelta.canceled += instance.OnMouseDelta;
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @NormalShoot.started += instance.OnNormalShoot;
            @NormalShoot.performed += instance.OnNormalShoot;
            @NormalShoot.canceled += instance.OnNormalShoot;
        }

        private void UnregisterCallbacks(IPlayerTopActions instance)
        {
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
            @MouseDelta.started -= instance.OnMouseDelta;
            @MouseDelta.performed -= instance.OnMouseDelta;
            @MouseDelta.canceled -= instance.OnMouseDelta;
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @NormalShoot.started -= instance.OnNormalShoot;
            @NormalShoot.performed -= instance.OnNormalShoot;
            @NormalShoot.canceled -= instance.OnNormalShoot;
        }

        public void RemoveCallbacks(IPlayerTopActions instance)
        {
            if (m_Wrapper.m_PlayerTopActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerTopActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerTopActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerTopActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerTopActions @PlayerTop => new PlayerTopActions(this);
    private int m_PlayerTopSchemeIndex = -1;
    public InputControlScheme PlayerTopScheme
    {
        get
        {
            if (m_PlayerTopSchemeIndex == -1) m_PlayerTopSchemeIndex = asset.FindControlSchemeIndex("PlayerTop");
            return asset.controlSchemes[m_PlayerTopSchemeIndex];
        }
    }
    public interface IPlayerThirdActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnRoll(InputAction.CallbackContext context);
        void OnHover(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnMoveUpDown(InputAction.CallbackContext context);
    }
    public interface IPlayerTopActions
    {
        void OnMousePosition(InputAction.CallbackContext context);
        void OnMouseDelta(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnNormalShoot(InputAction.CallbackContext context);
    }
}
