//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""PlayerThird"",
            ""id"": ""075ec289-1fc7-417d-af9b-af4759989350"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""5bebd4fe-e1a1-4f4d-8b73-585e79a11642"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""d7098c74-0170-45c9-bd5c-b992211345ef"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Roll"",
                    ""type"": ""Value"",
                    ""id"": ""8d09e5d7-fc9b-4712-b4eb-cc1e2643e923"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Hover"",
                    ""type"": ""Value"",
                    ""id"": ""c89d8863-bf46-41ed-ae92-8a1928f64904"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""16a1f49e-9a5e-40c0-8ed4-a6a34fe67c69"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveUpDown"",
                    ""type"": ""Button"",
                    ""id"": ""6df30f50-0170-42a2-9cae-7e69c4576332"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""05cbbae2-6a1f-4f65-9d53-9c181f0da8e9"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""b8c47fa5-cbb2-4768-8b3a-d87ea3c2a9bd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c8f03f8f-37a4-48d1-bc0c-3a170041c625"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""23a6f55c-1d85-40b1-8dfe-927df02e90e7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f044e3a2-278c-43f9-b615-d97d4948734d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1e338839-2557-4c68-9c46-edc64319c928"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""599c0ad5-b016-4741-9bbf-17fa9828b428"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0115551a-c8c8-49ed-9e20-3f906b192148"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""EQ"",
                    ""id"": ""0bdcd6f7-c12f-4ac1-ab9c-6cae0ad03424"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8c17c2db-230b-43d4-9c41-a866ba840df3"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""95ce723a-98ba-41c1-a59a-b434c7a9cce8"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftCtrlSpace"",
                    ""id"": ""0c2545d1-452b-467e-bf71-2923bbcd6246"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUpDown"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""9d05ea01-e020-46f9-84e3-be3bdbf8e306"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""726b03ff-9ae6-4275-a00d-f0dc623a18e0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""PlayerTop"",
            ""id"": ""0fae9da2-1901-4237-b840-88f81cc10e0b"",
            ""actions"": [
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""263c46ef-8530-4d42-a7ab-b8421577cc59"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseDelta"",
                    ""type"": ""Value"",
                    ""id"": ""933cc4fe-20b3-469c-ad1b-19ff22c0e458"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""188cb7af-eba0-4370-99f0-681dc6ab38a6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NormalShoot"",
                    ""type"": ""Button"",
                    ""id"": ""9d0866e0-abec-4cb8-aeb4-d0ef24bd6556"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""00c46c16-cc51-4481-9977-7e891d08af91"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae48b486-6e26-463f-b59c-6603a1a5a914"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""46018e52-9aae-4d06-ac62-420a8e65ada4"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""576189f1-0ed9-44be-8769-cc119103150e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""69efe525-aae7-4bd8-91af-aba3a72b4287"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0b22c807-5e00-43e3-8c77-61e7771fd151"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7109cce4-af85-4196-8671-ff78932bd4d8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7f0b5240-22a9-4087-a7b6-cbfe53177c3d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NormalShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PlayerTop"",
            ""bindingGroup"": ""PlayerTop"",
            ""devices"": []
        }
    ]
}");
        // PlayerThird
        m_PlayerThird = asset.FindActionMap("PlayerThird", throwIfNotFound: true);
        m_PlayerThird_Move = m_PlayerThird.FindAction("Move", throwIfNotFound: true);
        m_PlayerThird_Look = m_PlayerThird.FindAction("Look", throwIfNotFound: true);
        m_PlayerThird_Roll = m_PlayerThird.FindAction("Roll", throwIfNotFound: true);
        m_PlayerThird_Hover = m_PlayerThird.FindAction("Hover", throwIfNotFound: true);
        m_PlayerThird_Shoot = m_PlayerThird.FindAction("Shoot", throwIfNotFound: true);
        m_PlayerThird_MoveUpDown = m_PlayerThird.FindAction("MoveUpDown", throwIfNotFound: true);
        // PlayerTop
        m_PlayerTop = asset.FindActionMap("PlayerTop", throwIfNotFound: true);
        m_PlayerTop_MousePosition = m_PlayerTop.FindAction("MousePosition", throwIfNotFound: true);
        m_PlayerTop_MouseDelta = m_PlayerTop.FindAction("MouseDelta", throwIfNotFound: true);
        m_PlayerTop_Movement = m_PlayerTop.FindAction("Movement", throwIfNotFound: true);
        m_PlayerTop_NormalShoot = m_PlayerTop.FindAction("NormalShoot", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerThird
    private readonly InputActionMap m_PlayerThird;
    private List<IPlayerThirdActions> m_PlayerThirdActionsCallbackInterfaces = new List<IPlayerThirdActions>();
    private readonly InputAction m_PlayerThird_Move;
    private readonly InputAction m_PlayerThird_Look;
    private readonly InputAction m_PlayerThird_Roll;
    private readonly InputAction m_PlayerThird_Hover;
    private readonly InputAction m_PlayerThird_Shoot;
    private readonly InputAction m_PlayerThird_MoveUpDown;
    public struct PlayerThirdActions
    {
        private @Controls m_Wrapper;
        public PlayerThirdActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerThird_Move;
        public InputAction @Look => m_Wrapper.m_PlayerThird_Look;
        public InputAction @Roll => m_Wrapper.m_PlayerThird_Roll;
        public InputAction @Hover => m_Wrapper.m_PlayerThird_Hover;
        public InputAction @Shoot => m_Wrapper.m_PlayerThird_Shoot;
        public InputAction @MoveUpDown => m_Wrapper.m_PlayerThird_MoveUpDown;
        public InputActionMap Get() { return m_Wrapper.m_PlayerThird; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerThirdActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerThirdActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerThirdActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerThirdActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Roll.started += instance.OnRoll;
            @Roll.performed += instance.OnRoll;
            @Roll.canceled += instance.OnRoll;
            @Hover.started += instance.OnHover;
            @Hover.performed += instance.OnHover;
            @Hover.canceled += instance.OnHover;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @MoveUpDown.started += instance.OnMoveUpDown;
            @MoveUpDown.performed += instance.OnMoveUpDown;
            @MoveUpDown.canceled += instance.OnMoveUpDown;
        }

        private void UnregisterCallbacks(IPlayerThirdActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Roll.started -= instance.OnRoll;
            @Roll.performed -= instance.OnRoll;
            @Roll.canceled -= instance.OnRoll;
            @Hover.started -= instance.OnHover;
            @Hover.performed -= instance.OnHover;
            @Hover.canceled -= instance.OnHover;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @MoveUpDown.started -= instance.OnMoveUpDown;
            @MoveUpDown.performed -= instance.OnMoveUpDown;
            @MoveUpDown.canceled -= instance.OnMoveUpDown;
        }

        public void RemoveCallbacks(IPlayerThirdActions instance)
        {
            if (m_Wrapper.m_PlayerThirdActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerThirdActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerThirdActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerThirdActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerThirdActions @PlayerThird => new PlayerThirdActions(this);

    // PlayerTop
    private readonly InputActionMap m_PlayerTop;
    private List<IPlayerTopActions> m_PlayerTopActionsCallbackInterfaces = new List<IPlayerTopActions>();
    private readonly InputAction m_PlayerTop_MousePosition;
    private readonly InputAction m_PlayerTop_MouseDelta;
    private readonly InputAction m_PlayerTop_Movement;
    private readonly InputAction m_PlayerTop_NormalShoot;
    public struct PlayerTopActions
    {
        private @Controls m_Wrapper;
        public PlayerTopActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MousePosition => m_Wrapper.m_PlayerTop_MousePosition;
        public InputAction @MouseDelta => m_Wrapper.m_PlayerTop_MouseDelta;
        public InputAction @Movement => m_Wrapper.m_PlayerTop_Movement;
        public InputAction @NormalShoot => m_Wrapper.m_PlayerTop_NormalShoot;
        public InputActionMap Get() { return m_Wrapper.m_PlayerTop; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerTopActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerTopActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerTopActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerTopActionsCallbackInterfaces.Add(instance);
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
            @MouseDelta.started += instance.OnMouseDelta;
            @MouseDelta.performed += instance.OnMouseDelta;
            @MouseDelta.canceled += instance.OnMouseDelta;
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @NormalShoot.started += instance.OnNormalShoot;
            @NormalShoot.performed += instance.OnNormalShoot;
            @NormalShoot.canceled += instance.OnNormalShoot;
        }

        private void UnregisterCallbacks(IPlayerTopActions instance)
        {
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
            @MouseDelta.started -= instance.OnMouseDelta;
            @MouseDelta.performed -= instance.OnMouseDelta;
            @MouseDelta.canceled -= instance.OnMouseDelta;
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @NormalShoot.started -= instance.OnNormalShoot;
            @NormalShoot.performed -= instance.OnNormalShoot;
            @NormalShoot.canceled -= instance.OnNormalShoot;
        }

        public void RemoveCallbacks(IPlayerTopActions instance)
        {
            if (m_Wrapper.m_PlayerTopActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerTopActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerTopActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerTopActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerTopActions @PlayerTop => new PlayerTopActions(this);
    private int m_PlayerTopSchemeIndex = -1;
    public InputControlScheme PlayerTopScheme
    {
        get
        {
            if (m_PlayerTopSchemeIndex == -1) m_PlayerTopSchemeIndex = asset.FindControlSchemeIndex("PlayerTop");
            return asset.controlSchemes[m_PlayerTopSchemeIndex];
        }
    }
    public interface IPlayerThirdActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnRoll(InputAction.CallbackContext context);
        void OnHover(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnMoveUpDown(InputAction.CallbackContext context);
    }
    public interface IPlayerTopActions
    {
        void OnMousePosition(InputAction.CallbackContext context);
        void OnMouseDelta(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnNormalShoot(InputAction.CallbackContext context);
    }
}
